channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=20.0.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - psutil==5.9.8
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
